aliases:
  CCTV-1 综合: [CCTV1, CCTV 1, CCTV-1, 中央一套, 中央电视台综合频道]
  CCTV-2 财经: [CCTV2, CCTV 2, CCTV-2, 中央二套, 中央电视台财经频道]
  CCTV-3 综艺: [CCTV3, CCTV 3, CCTV-3, 中央三套, 中央电视台综艺频道]
  CCTV-4 中文国际: [CCTV4, CCTV 4, CCTV-4, 中央四套, 中央电视台中文国际频道]
  CCTV-5 体育: [CCTV5, CCTV 5, CCTV-5, CCTV5 体育1, CCTV5 体育2, CCTV5 体育3, 中央五套, 中央电视台体育频道]
  CCTV-5+ 体育赛事: [CCTV5+, CCTV-5+, CCTV 5+, CCTV5 Plus, CCTV5+ 体育赛事1, CCTV5+ 体育赛事2, CCTV5+ 体育赛事3, 中央五套+, 体育赛事频道]
  CCTV-6 电影: [CCTV6, CCTV 6, CCTV-6, 中央六套, 中央电视台电影频道]
  CCTV-7 国防军事: [CCTV7, CCTV 7, CCTV-7, 中央七套, 中央电视台国防军事频道]
  CCTV-8 电视剧: [CCTV8, CCTV 8, CCTV-8, CCTV-8 (720p), 中央八套, 中央电视台电视剧频道]
  CCTV-9 纪录: [CCTV9, CCTV 9, CCTV-9, 中央九套, 中央电视台纪录频道]
  CCTV-10 科教: [CCTV10, CCTV 10, CCTV-10, 中央十套, 中央电视台科教频道]
  CCTV-11 戏曲: [CCTV11, CCTV 11, CCTV-11, 中央十一套, 中央电视台戏曲频道]
  CCTV-12 社会与法: [CCTV12, CCTV 12, CCTV-12, 中央十二套, 中央电视台社会与法频道]
  CCTV-13 新闻: [CCTV13, CCTV 13, CCTV-13, 中央十三套, 中央电视台新闻频道]
  CCTV-14 少儿: [CCTV14, CCTV 14, CCTV-14, 中央十四套, 中央电视台少儿频道]
  CCTV-15 音乐: [CCTV15, CCTV 15, CCTV-15, 中央十五套, 中央电视台音乐频道]
  CCTV-16 奥林匹克: [CCTV16, CCTV 16, CCTV-16, 中央十六套, 中央电视台奥林匹克频道]
  CCTV-17 农业农村: [CCTV17, CCTV 17, CCTV-17, 中央十七套, 中央电视台农业农村频道]
  湖南卫视: [湖南台, 湖南卫视HD, Hunan TV]
  浙江卫视: [浙江台, 浙江卫视HD, Zhejiang Satellite TV]
  江苏卫视: [江苏台, 江苏卫视HD, Jiangsu Satellite TV]
  东方卫视: [上海东方卫视, 东方台, 东方卫视HD]
  北京卫视: [北京台, BTV卫视, 北京卫视HD, Beijing Satellite TV]
  广东卫视: [广东台, 广东卫视HD, Guangdong Satellite TV]
  深圳卫视: [深圳台, 深圳卫视HD, Shenzhen Satellite TV]
  山东卫视: [山东台, 山东卫视HD, Shandong Satellite TV, Shandong TV]
  安徽卫视: [安徽台, 安徽卫视HD, Anhui TV]
  天津卫视: [天津台, 天津卫视HD, Tianjin TV]
  湖北卫视: [湖北台, 湖北卫视HD]
  四川卫视: [四川台, 四川卫视HD, Sichuan Satellite TV]
  重庆卫视: [重庆台, 重庆卫视HD]
  河南卫视: [河南台, 河南卫视HD]
  河北卫视: [河北台, 河北卫视HD, Hebei TV]
  辽宁卫视: [辽宁台, 辽宁卫视HD, Liaoning TV]
  江西卫视: [江西台, 江西卫视HD, Jiangxi TV]
  东南卫视: [福建东南卫视, 东南台, 东南卫视HD]
  广西卫视: [广西台, 广西卫视HD]
  贵州卫视: [贵州台, 贵州卫视HD, Guizhou TV]
  云南卫视: [云南台, 云南卫视HD, Yunnan Satellite TV]
  黑龙江卫视: [黑龙江台, 黑龙江卫视HD, Heilongjiang TV]
  广东新闻: [广东新闻频道, "广东新闻[1920x1080]"]
  广东体育: [广东体育频道, "广东体育[1920x1080]"]
  广东民生: [广东民生频道, "广东民生[1920x1080]"]
  广东影视: [广东影视频道, "广东影视[1920x1080]"]
  广东珠江: ["广东珠江[1920x1080]"]
  南方卫视: [南方卫视HD, 广东南方卫视, TVS-2]
  汕头综合: [汕头综合HD, 汕头新闻综合, 汕头一套, 广东汕头综合]
  汕头经济: [汕头经济HD, 汕头二套]
  汕头体育: [汕头体育HD, 汕头三套]
  广东少儿: [广东少儿频道, "广东少儿[1920x1080]"]
  广东科教: ["广东科教[1920x1080]"]
